-- Schema for GAUGE_INVENTORY (PostgreSQL)
-- Generated for: localhost:2424, db GAUGE_INVENTORY

-- 1) users
CREATE TABLE IF NOT EXISTS public.users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role          VARCHAR(20)  NOT NULL,
  email         VARCHAR(100) NOT NULL UNIQUE,
  created_at    TIMESTAMP    NOT NULL DEFAULT now()
);

-- 2) equipment_used_for_calibration
CREATE TABLE IF NOT EXISTS public.equipment_used_for_calibration (
  gauge_id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_of_the_equipment           VARCHAR(100) NOT NULL,
  location                        VARCHAR(100),
  receipt_date                    DATE,
  make_model                      VARCHAR(100),
  idfn_no                         VARCHAR(100),
  overall_measurement_uncertainty VARCHAR(100),
  calibration_freq_months         INT,
  date_of_last_calibration        DATE,
  calibration_due                 DATE,
  pcr_number                      INT
);

-- 3) gauges
CREATE TABLE IF NOT EXISTS public.gauges (
  gauge_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  serial_number VARCHAR(100),
  manufacturer  VARCHAR(100),
  location      VARCHAR(100),
  status        VARCHAR(20),
  added_by      INT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_gauges_added_by ON public.gauges(added_by);

-- 4) calibration_schedule
CREATE TABLE IF NOT EXISTS public.calibration_schedule (
  schedule_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gauge_id          INT NOT NULL REFERENCES public.gauges(gauge_id) ON DELETE CASCADE,
  last_calibration  DATE,
  next_due_date     DATE,
  frequency_type    VARCHAR(20),
  frequency_value   INT,
  notification_sent BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_cal_sched_gauge_id ON public.calibration_schedule(gauge_id);

-- 5) calibration_history
CREATE TABLE IF NOT EXISTS public.calibration_history (
  calibration_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gauge_id         INT NOT NULL REFERENCES public.gauges(gauge_id) ON DELETE CASCADE,
  calibration_date DATE,
  status           VARCHAR(20),
  comments         TEXT,
  approved_by      INT REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_cal_hist_gauge_id ON public.calibration_history(gauge_id);
CREATE INDEX IF NOT EXISTS idx_cal_hist_approved_by ON public.calibration_history(approved_by);

-- 6) gauge_tracker
CREATE TABLE IF NOT EXISTS public.gauge_tracker (
  transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gauge_id       INT NOT NULL REFERENCES public.gauges(gauge_id) ON DELETE CASCADE,
  issued_to      INT REFERENCES public.users(id) ON DELETE SET NULL,
  issued_at      TIMESTAMP,
  returned_at    TIMESTAMP,
  status         VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS idx_gauge_tracker_gauge_id ON public.gauge_tracker(gauge_id);
CREATE INDEX IF NOT EXISTS idx_gauge_tracker_issued_to ON public.gauge_tracker(issued_to);

-- 7) notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INT REFERENCES public.users(id) ON DELETE CASCADE,
  gauge_id        INT REFERENCES public.gauges(gauge_id) ON DELETE CASCADE,
  message         TEXT,
  sent_at         TIMESTAMP NOT NULL DEFAULT now(),
  read_status     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_gauge_id ON public.notifications(gauge_id);
