// Lightweight JS loader for jsPDF + autoTable via CDN, no npm dependency
let jsPdfPromise = null

export async function loadJsPDF() {
  if (window.jspdf && window.jspdf.jsPDF && window.jspdf.jsPDF.prototype) {
    return window.jspdf.jsPDF
  }
  if (!jsPdfPromise) {
    jsPdfPromise = new Promise((resolve, reject) => {
      const addScript = (src) => new Promise((res, rej) => {
        const s = document.createElement('script')
        s.src = src
        s.async = true
        s.onload = () => res()
        s.onerror = () => rej(new Error('Failed to load ' + src))
        document.head.appendChild(s)
      })
      ;(async () => {
        try {
          await addScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js')
          await addScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.5.28/dist/jspdf.plugin.autotable.min.js')
          if (window.jspdf && window.jspdf.jsPDF) {
            resolve(window.jspdf.jsPDF)
          } else {
            reject(new Error('jsPDF not available'))
          }
        } catch (e) { reject(e) }
      })()
    })
  }
  return jsPdfPromise
}

export function formatNow() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}`
}

export function makeHeaderFooter(doc, title) {
  // Deprecated: left for backward-compat if needed elsewhere. Prefer using didDrawPage hook via buildAutoTablePageHook.
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    // Header area (top margin reserved by autoTable margin.top)
    doc.setFontSize(12)
    doc.text(title, 14, 12)
    const ts = new Date().toLocaleString()
    doc.setFontSize(8)
    doc.text(`Exported: ${ts}`, 14, 18)
    doc.text('Organization: CMTI', width - 14, 12, { align: 'right' })
    // Footer
    doc.setFontSize(8)
    const footerText = `Generated by Gauge System  |  Page ${i} of ${pageCount}`
    doc.text(footerText, width / 2, height - 8, { align: 'center' })
  }
}

// Lightweight loader for html2canvas via CDN
let html2canvasPromise = null
export async function loadHtml2Canvas() {
  if (window.html2canvas && typeof window.html2canvas === 'function') return window.html2canvas
  if (!html2canvasPromise) {
    html2canvasPromise = new Promise((resolve, reject) => {
      const s = document.createElement('script')
      s.src = 'https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js'
      s.async = true
      s.onload = () => resolve(window.html2canvas)
      s.onerror = () => reject(new Error('Failed to load html2canvas'))
      document.head.appendChild(s)
    })
  }
  return html2canvasPromise
}

// Export a DOM element to a paginated PDF (A4 portrait)
export async function exportElementToPDF(element, fileName, title = 'Analytics') {
  const jsPDF = await loadJsPDF()
  const html2canvas = await loadHtml2Canvas()
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })

  const a4Width = doc.internal.pageSize.getWidth()
  const a4Height = doc.internal.pageSize.getHeight()

  // Render at higher scale for clarity
  const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#ffffff' })
  const imgData = canvas.toDataURL('image/png')
  const imgWidth = a4Width - 40 // margins
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  let y = 40
  let remainingHeight = imgHeight
  let srcY = 0
  const pageMarginBottom = 30

  // Draw header on each page
  const drawHeader = () => {
    doc.setFontSize(12)
    doc.text(String(title || ''), 20, 24)
    doc.setFontSize(8)
    doc.text(`Exported: ${new Date().toLocaleString()}`, 20, 34)
  }

  // We will slice the tall canvas into page segments by drawing with different y positions
  while (remainingHeight > 0) {
    drawHeader()
    const available = a4Height - y - pageMarginBottom
    const h = Math.min(remainingHeight, available)

    // Add the image segment
    doc.addImage(imgData, 'PNG', 20, y, imgWidth, (h))

    remainingHeight -= available
    if (remainingHeight > 0) {
      doc.addPage()
      y = 40
    }
  }

  doc.save(fileName || `export_${formatNow()}.pdf`)
}

// Preferred: use this hook with jsPDF autoTable to draw header/footer on every page
// without overlapping table content. Also set margin.top/bottom in autoTable options.
export function buildAutoTablePageHook(doc, title) {
  return function didDrawPageHook(data) {
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber
    const pageCount = doc.internal.getNumberOfPages()
    // Header within reserved top margin
    doc.setFontSize(12)
    doc.text(title, 14, 12)
    const ts = new Date().toLocaleString()
    doc.setFontSize(8)
    doc.text(`Exported: ${ts}`, 14, 18)
    doc.text('Organization: CMTI', width - 14, 12, { align: 'right' })
    // Footer within reserved bottom margin
    doc.setFontSize(8)
    const footerText = `Generated by Gauge System  |  Page ${pageNumber} of ${pageCount}`
    doc.text(footerText, width / 2, height - 8, { align: 'center' })
  }
}
