// Lightweight JS loader for jsPDF + autoTable via CDN, no npm dependency
let jsPdfPromise = null

export async function loadJsPDF() {
  if (window.jspdf && window.jspdf.jsPDF && window.jspdf.jsPDF.prototype) {
    return window.jspdf.jsPDF
  }
  if (!jsPdfPromise) {
    jsPdfPromise = new Promise((resolve, reject) => {
      const addScript = (src) => new Promise((res, rej) => {
        const s = document.createElement('script')
        s.src = src
        s.async = true
        s.onload = () => res()
        s.onerror = () => rej(new Error('Failed to load ' + src))
        document.head.appendChild(s)
      })
      ;(async () => {
        try {
          await addScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js')
          await addScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.5.28/dist/jspdf.plugin.autotable.min.js')
          if (window.jspdf && window.jspdf.jsPDF) {
            resolve(window.jspdf.jsPDF)
          } else {
            reject(new Error('jsPDF not available'))
          }
        } catch (e) { reject(e) }
      })()
    })
  }
  return jsPdfPromise
}

export function formatNow() {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}`
}

export function makeHeaderFooter(doc, title) {
  // Deprecated: left for backward-compat if needed elsewhere. Prefer using didDrawPage hook via buildAutoTablePageHook.
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    // Header area (top margin reserved by autoTable margin.top)
    doc.setFontSize(12)
    doc.text(title, 14, 12)
    const ts = new Date().toLocaleString()
    doc.setFontSize(8)
    doc.text(`Exported: ${ts}`, 14, 18)
    doc.text('Organization: CMTI', width - 14, 12, { align: 'right' })
    // Footer
    doc.setFontSize(8)
    const footerText = `Generated by Gauge System  |  Page ${i} of ${pageCount}`
    doc.text(footerText, width / 2, height - 8, { align: 'center' })
  }
}

// Preferred: use this hook with jsPDF autoTable to draw header/footer on every page
// without overlapping table content. Also set margin.top/bottom in autoTable options.
export function buildAutoTablePageHook(doc, title) {
  return function didDrawPageHook(data) {
    const width = doc.internal.pageSize.getWidth()
    const height = doc.internal.pageSize.getHeight()
    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber
    const pageCount = doc.internal.getNumberOfPages()
    // Header within reserved top margin
    doc.setFontSize(12)
    doc.text(title, 14, 12)
    const ts = new Date().toLocaleString()
    doc.setFontSize(8)
    doc.text(`Exported: ${ts}`, 14, 18)
    doc.text('Organization: CMTI', width - 14, 12, { align: 'right' })
    // Footer within reserved bottom margin
    doc.setFontSize(8)
    const footerText = `Generated by Gauge System  |  Page ${pageNumber} of ${pageCount}`
    doc.text(footerText, width / 2, height - 8, { align: 'center' })
  }
}
